import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    width: '90%',
    paddingBottom: 280,
    backgroundColor: '#ffffff',
  },
  logoContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mensagemSenha: {
    // right: 12,
    //flex:1,
    justifyContent: 'flex-start',
    color: '#ff0000',
  },
  mensagemConfirmarSenha: {
    justifyContent: 'flex-start',
    color: '#ff0000',
  },
  mensagemNome: {
    justifyContent: 'flex-start',
    color: '#ff0000',
  },
  mensagemEmail: {
    justifyContent: 'flex-start',
    color: '#ff0000',
  },
  inputNome: {
    backgroundColor: '#ffffff',
    width: '90%',
    marginBottom: 15,
    color: '#000000',
    fontSize: 17,
    padding: 10,
    borderBottomWidth: 2,
    borderColor: '#000000',
    fontFamily: 'Outfit-Regular',
    paddingLeft: 40,
  },
  inputEmail: {
    backgroundColor: '#ffffff',
    width: '90%',
    marginBottom: 15,
    color: '#000000',
    fontSize: 17,
    padding: 10,
    borderBottomWidth: 2,
    borderColor: '#000000',
    fontFamily: 'Outfit-Regular',
    paddingLeft: 40,
  },

  inputSenha: {
    backgroundColor: '#ffffff',
    width: '90%',
    marginBottom: 15,
    color: '#000000',
    fontSize: 17,
    padding: 10,
    borderBottomWidth: 2,
    borderColor: '#000000',
    fontFamily: 'Outfit-Regular',
    paddingLeft: 40,
  },
  inputConfirmarSenha: {
    backgroundColor: '#ffffff',
    width: '90%',
    marginBottom: 15,
    color: '#000000',
    fontSize: 17,
    padding: 10,
    borderBottomWidth: 2,
    borderColor: '#000000',
    fontFamily: 'Outfit-Regular',
    paddingLeft: 40,
  },
  IconUser: {
    position: 'absolute',
    top: 8,
    left: 25,
  },
  IconSenha: {
    position: 'absolute',
    top: 174,
    left: 25,
  },
  IconEmail: {
    position: 'absolute',
    top: 95,
    left: 25,
  },
  IconConfirmarSenha: {
    position: 'absolute',
    top: 257,
    left: 25,
  },
  background: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
  },
  // fix the position of the icons when keyboard is up
  btnSubmit: {
    backgroundColor: '#48BF84',
    width: '90%',
    height: 45,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 7,
    // paddingTop: 50,
  },
  submitText: {
    color: '#ffffff',
    fontSize: 18,
    //fontWeight: 'bold',
    fontFamily: 'Outfit-SemiBold',
  },
});
